### ISSUE TITLE
add run shortcut and/or hot reload 

### ISSUE THREAD

**Issue by ascorbic-acid** [ronakdev/console#1]
hey, 
is it possible to add hot reload features and run shortcut like ctrl + enter ?
thanks

**Comment by trulyronak** [comment]
I added the features you asked for, in addition to code saving. I tested it on Chrome and Safari.

Keyboard Shortcuts:
- ctrl/cmd enter : run code
- ctrl/cmd s : save code
- ctrl/cmd l : clear console

If you have any other ideas, feel free to post them here, I love adding new stuff!

**Comment by ascorbic-acid** [comment]
thanks, now much easier to work with :)
