### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Epi-JJones** [ronakdev/console#2]
Is this shared under a specific license? Public domain? A Creative Commons license? GNU, MIT, Apache, etc? That should be included in the readme (and possibly in the header comment of the sample code) so folks know what rights they have -- usage, distribution, restrictions, etc.

Thanks!

**Comment by trulyronak** [comment]
Thanks for pointing that out, I  added one 

You may use it freely, distribute it (for free, and giving me credit), and I am not liable for any code you write on it.
 
https://github.com/ronakdev/console/blob/master/LICENSE
